Refactor static request handler extensions
siemens/simatic-s7-webserver-api pull request #7
Opened 2021-11-10 19:21 UTC by KircMax

- Restructure folder structure (and namespaces) => Implement Services Folder
- MakeSureRequestIdsAreUnique => add optional timeOut
- ApiPlcProgramData: Implement ArrayElements (set by Setter of ArrayDimensions) - remember to add the Parents!
> - override ToString() for debugging comfort
> - adjust GetNameWithQuotes => for arrayElements indexes have to be outside of the quotes!
- Refactor static Extensions:
> - Implement ApiResourceHandler
> - Implement IApiWebAppResourceBuilder, ApiWebAppResourceBuilder
> - move IApiRequestHandler functionality to IAsyncApiRequestHandler, rename to IApiRequestHandler => also implement non-async functionality (by awaiting async methods)
> - Deployer : use ApiResourceHandler
> - Implement ApiPlcProgramHandler
- Implement IIdGenerator
- RequestFactory: Make use of IIdGenerator
- ConnectionConfiguration: set clear default values
- Update nuget packages
- Update version => new Major (changed namespaces,...)

-Problems:
> - Csproj: cannot use ContinuousIntegrationBuild true for SourceLink anymore ?
> - ApiPlcProgramHandler: WriteStructByChildValues for (multi-dim) arrays

2021-11-11 12:25 UTC, KircMax commented
Maybe no new major version would be necessary if we re-add the Extension methods and mark them as deprecated so that current code will still work ?
open:
- Write Structs with (multidim) arrays
- SourceLink issues

2021-11-16 06:32 UTC, KircMax commented
Should we maybe also add a DownloadResourceSetting?

2021-11-16 06:59 UTC, KircMax commented
Todo: update readme

2021-11-16 09:50 UTC, TheKoolPie requested changes

2021-11-16 09:50 UTC, TheKoolPie commented on src/Webserver.API/Services/WebApp/ApiResourceHandler.cs
> +                throw ex;
With this the stacktrace will not be changed
```suggestion
                throw;
```

2021-11-16 09:50 UTC, TheKoolPie commented on src/Webserver.API/Services/WebApp/ApiResourceHandler.cs
> +            string usedPathToDownloadDirectory = pathToDownloadDirectory ?? Environment.GetFolderPath(Environment.SpecialFolder.Desktop).Replace("Desktop", "Downloads");
also do a Directory exists and for the others File exists

2021-11-16 09:50 UTC, TheKoolPie commented on tests/Webserver.API.UnitTests/ApiBulkTests.cs
> +        public void ApiBulk_RequestsSameId()
With unit test functions it would be nice to add also the expected result to the name, like: 
```suggestion
        public void ApiBulk_RequestsSameId_ThrowsArgumentException()

```

2021-11-16 09:50 UTC, TheKoolPie commented on tests/Webserver.API.UnitTests/ApiWebAppDataSaverTests.cs
> +        public void SaveThrowsIfDirectoryDoesNotExistForSetting()
empty test

2021-11-16 09:50 UTC, TheKoolPie commented on tests/Webserver.API.UnitTests/RequestParameterCheckerTests.cs
> +            //Assert.Throws<ApiInvalidParametersException>(() => requestParameterChecker.CheckLastModified(DateTime.Now.ToString(), true));
uncommented still needed?

2021-11-17 16:58 UTC, KircMax commented on tests/Webserver.API.UnitTests/RequestParameterCheckerTests.cs
> +            //Assert.Throws<ApiInvalidParametersException>(() => requestParameterChecker.CheckLastModified(DateTime.Now.ToString(), true));
yes - we just don't have a "very clear" last modified regex to check for so we accept all currently (the commented ones shouldnt work currently

2021-11-17 17:02 UTC, KircMax commented on src/Webserver.API/Services/WebApp/ApiResourceHandler.cs
> +            string usedPathToDownloadDirectory = pathToDownloadDirectory ?? Environment.GetFolderPath(Environment.SpecialFolder.Desktop).Replace("Desktop", "Downloads");
What do you mean for "the others File exists"? - there is a check:
![image](https://user-images.githubusercontent.com/47225814/142247058-f78661ad-0e33-416e-a2b3-ec91c468ed11.png)

2021-11-17 17:04 UTC, KircMax commented on src/Webserver.API/Models/ApiWebAppDataSaveSetting.cs
> +    public class ApiWebAppDataSaveSetting : IApiWebAppDataSaveSetting
done

2021-11-17 17:08 UTC, KircMax commented on src/Webserver.API/Models/ApiWebAppDataSaveSetting.cs
> +        public bool CheckConsistency { get; set; }
Yes - At least I think it's the most comfortable way for a "user" to control the WebAppDataSaver (in case he wants to change some defaults/etc.)

2021-11-17 17:13 UTC, KircMax commented on src/Webserver.API/Models/ApiPlcProgramData.cs
> +            if (IsArrayElement)
done

2021-11-17 17:17 UTC, KircMax commented on src/Webserver.API/Models/ApiPlcProgramData.cs
> +                this.ArrayElements = BuildChildrenFromArrayDimensions(_arrayDimensions);
Well yes but ArrayDimensions will not be returned by the plc in case the plcprogramdata does not have any so the setter will not be "run into" - should we not build the children "in case of null" anyways?

2021-11-17 17:33 UTC, KircMax commented on tests/Webserver.API.UnitTests/ApiWebAppDataSaverTests.cs
> +        public void SaveThrowsIfDirectoryDoesNotExistForSetting()
deleted

2021-11-17 17:33 UTC, KircMax commented on tests/Webserver.API.UnitTests/ApiBulkTests.cs
> +        public void ApiBulk_RequestsSameId()
applied for many unit tests

2021-11-17 17:34 UTC, KircMax commented on src/Webserver.API/Services/WebApp/ApiResourceHandler.cs
> +                throw ex;
done

2021-11-17 17:34 UTC, KircMax commented on src/Webserver.API/Models/ApiPlcProgramData.cs
> +        ///
done

2021-11-18 13:50 UTC, TheKoolPie commented on src/Webserver.API/Models/ApiPlcProgramData.cs
> +                this.ArrayElements = BuildChildrenFromArrayDimensions(_arrayDimensions);
As its a public setter, I would say its better to perform null check and throw readable error

2021-11-18 13:51 UTC, TheKoolPie commented on src/Webserver.API/Models/ApiWebAppDataSaveSetting.cs
> +        public bool CheckConsistency { get; set; }
Then please add more value to the summaries of each property

2021-11-18 13:52 UTC, TheKoolPie commented on src/Webserver.API/Models/HttpClientConnectionConfiguration.cs
>  ﻿// Copyright (c) 2021, Siemens AG
@KircMax  whats up with this class?

2021-11-18 14:07 UTC, TheKoolPie commented on src/Webserver.API/Services/RequestHandling/ApiResponseChecker.cs
> +            return true;
Always the same?

2021-11-18 14:08 UTC, KircMax commented on src/Webserver.API/Services/RequestHandling/ApiResponseChecker.cs
> +            return true;
I don't have any Properties to compare here so any ApiResponseChecker basically Equals an ApiResponseChecker (without overriding this would not be the case that's all the reason the override was implemented)

2021-11-18 14:12 UTC, TheKoolPie commented on src/Webserver.API/Services/WebApp/ApiResourceHandler.cs
> +        /// <param name="webApp">make sure to set the webapp PathToWebAppDirectory before calling this method!</param>
I think you can use <paramref .../> tag to make the webapp PathToWebAppDirectory more readable

2021-11-18 14:18 UTC, TheKoolPie commented on src/Webserver.API/Services/WebApp/ApiWebAppDataSaver.cs
> +            if (apiWebAppSaveSetting == null)
```suggestion
ApiWebAppSaveSetting = apiWebSaveSetting ?? throw new ArgumentNullException(...)
```

2021-11-18 14:21 UTC, TheKoolPie commented on src/Webserver.API/Services/WebApp/ApiWebAppDataSaver.cs
> +            else
else needed?

2021-11-18 14:26 UTC, TheKoolPie commented on tests/Webserver.API.UnitTests/ApiBulkTests.cs
> +        public async Task ApiBulk_RequestsUniqueIds_works()
```suggestion
        public async Task ApiBulk_Send100RequestsWithUniqueIds_Returns100SucessfulResponses()

```
A little more descriptive.

2021-11-18 14:30 UTC, TheKoolPie commented on tests/Webserver.API.UnitTests/ApiWebAppDataSaverTests.cs
> +            string dirPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "tmp");
Maybe run the tests in the current executing directory. With this you're sure you have access

2021-11-21 10:40 UTC, KircMax commented on src/Webserver.API/Models/ApiWebAppResource.cs
> +        public bool IsHtmlFile()
done

2021-11-21 10:40 UTC, KircMax commented on src/Webserver.API/Models/HttpClientConnectionConfiguration.cs
> +                _idGenerator = value;
refactored

2021-11-21 10:40 UTC, KircMax commented on src/Webserver.API/Models/HttpClientConnectionConfiguration.cs
> +                    ApiRequestFactory = new ApiRequestFactory(_idGenerator, RequestParameterChecker);
refactored

2021-11-21 10:40 UTC, KircMax commented on src/Webserver.API/Models/HttpClientConnectionConfiguration.cs
>  ﻿// Copyright (c) 2021, Siemens AG
refactored

2021-11-21 10:42 UTC, KircMax commented on src/Webserver.API/Models/Responses/ApiTicketIdResponse.cs
> +        public void CheckValidity(IApiRequestParameterChecker requestParameterChecker)
deleted

2021-11-21 10:43 UTC, KircMax commented on src/Webserver.API/Services/FileParser/WebAppConfigParser.cs
> +            ApiWebAppResourceBuilder = webAppResourceBuilder;
done

2021-11-21 15:04 UTC, KircMax commented on src/Webserver.API/Services/IdGenerator/IIdGenerator.cs
> +        int Length { get; set; }
adjusted

2021-11-21 15:04 UTC, KircMax commented on src/Webserver.API/Services/RequestHandling/ApiHttpClientAuthorizationHandler.cs
>  using Siemens.Simatic.S7.Webserver.API.Enums;
removed authorizationhandler in general => ServiceFactory

2021-11-21 15:13 UTC, KircMax commented on src/Webserver.API/Services/RequestHandling/IApiRequestParameterChecker.cs
> +        /// regex used: Regex regex = new Regex(@"\d{4}(-\d{2})(-\d{2})T(\d{2}):(\d{2}):(\d{2})(\.[0-9]{1,3})*Z"); string has to match!
adjusted accordingly

2021-11-21 15:25 UTC, KircMax commented on tests/Webserver.API.UnitTests/ApiWebAppDataSaverTests.cs
> +            string dirPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "tmp");
done

2021-11-21 15:26 UTC, KircMax commented on src/Webserver.API/Services/RequestHandling/IApiRequestFactory.cs
>  //
adjusted

2021-11-21 15:35 UTC, KircMax commented on src/Webserver.API/Models/ApiWebAppDataSaveSetting.cs
> +        public bool CheckConsistency { get; set; }
adjusted - makes sense to only be set in the c'tor!

2021-11-21 15:35 UTC, KircMax commented on src/Webserver.API/Services/PlcProgram/ApiPlcProgramHandler.cs
> +                    throw new Exception("Dont quite know how I landed here!");
done

2021-11-23 07:29 UTC, TheKoolPie approved these changes

2021-11-23 12:44 UTC, merged